### ISSUE TITLE
vbap crash

### ISSUE THREAD

**Issue by avilleret** [jamoma/JamomaDependencies#1]
here is a crash log I got today that seems to be related to vbap : https://gist.github.com/avilleret/172565756e1c06b6f6a2

I will post more infos if I can reproduce it.

**Comment by avilleret** [comment]
here is another crash : https://gist.github.com/avilleret/6ef69635def6a583cd16
it happens when loading a score into i-score 0.2.3b2 on OS X.
The score is here : https://github.com/avilleret/InteracSon/blob/master/Jardin%20de%20tabaldak.score
And the associated patch : https://github.com/avilleret/InteracSon/blob/master/_InteracSon.maxpat
(please checkout the whole repo and install packages before trying to open it)

**Comment by nwolek** [comment]
The method in question is calling getbytes and freebytes, which needs to be done carefully. If something has the wrong byte size, it could be the source of crash.

https://github.com/jamoma/JamomaDependencies/blob/master/Max/VBAP-1.03-w-source/source/vbap/vbap.c#L519

Too late here and I’m too tired to see the issues. Just making a note for later.

-Nathan

**Comment by nwolek** [comment]
First crash log is happening here: 
https://github.com/jamoma/JamomaDependencies/blob/master/Max/VBAP-1.03-w-source/source/vbap/vbap.c#L324

**Comment by nwolek** [comment]
Odd question: Do you have more than 55 loud speakers defined? That seems to be the limit in the code.

**Comment by avilleret** [comment]
I have just 4 speakers defined.
But I'm using severals instances of vbap at the same time (3 I think)
Now I'm working with the universal binary version of ee51da7e8deeec621db1ad5753fbca5a07b48667 and let you know if a crash happen.
Btw I was already working with 32bit Max.

**Comment by avilleret** [comment]
I got the same with old 32bit universal binary 
see the crash log here : https://gist.github.com/avilleret/c836efb2684e4c6876ac
I'll try to make a small patch that trigs this crash.

**Comment by nwolek** [comment]
So that means it pre-dates me doing the 64-bit update. 

The 55 maximum loud speaker question was just something I noticed in the code. Not sure how Ville arrived at that number, but sounds like it is unrelated.

**Comment by ChristopherFulham** [comment]
Hi guys, 
Do either of you possibly know if there are any VBAP 64 bit externals for MAX MSP for windows users? It's for an art installation i'm working on in Australia. Any direction would be fantastic.

**Comment by nwolek** [comment]
Saw this old issue while searching through my email inbox. There is now a separate repo with versions of the vbap external compiled for Mac and Windows here:

https://github.com/nwolek/vbap

Closing this issue.
